version: 2

project_name: rabbit-go

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: rabbit-go
    main: ./main.go

archives:
  - formats:                    # 改用 formats (复数)
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: rabbit
    repository:
      owner: ilpanda
      name: homebrew-repo
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: Formula           # 使用现有的 Formula 目录
    homepage: "https://github.com/ilpanda/rabbit-go"
    description: "Android ADB command line tool"
    license: "MIT"
    install: |
      bin.install "rabbit-go"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'